### ISSUE TITLE
Krypton beta2 crash with pvr stalker

### ISSUE THREAD

**Issue by Goga777** [kodi-pvr/pvr.stalker#74]
http://trac.kodi.tv/ticket/16905#comment:1

please fix that issue

**Comment by kenji123** [comment]
it should be possible to work around that error by changing the guide preference setting to xmltv-only

**Comment by Goga777** [comment]
I have already tried to use xmltv-only, but it didn't help me

**Comment by kenji123** [comment]
based on the log, changing that setting should skip over problem area. which is where it tries to read the json epg. maybe there's another error occurring elsewhere too

**Comment by Goga777** [comment]
I will try again with xml-only option and I will send the log if I will have kodi crash

**Comment by Goga777** [comment]
btw - is it possible to fix the kodi crach which I mentioned in the first bug report ?

**Comment by Goga777** [comment]
with xmltv option I don't have any crash. But I couldn't play any stream - there is error - failed to get stream url

18:33:17 T:2692740000   DEBUG: AddOnLog: Stalker Client: UnloadEPG
18:33:28 T:2863653792   DEBUG: Thread JobWorker 2863653792 terminating (autodelete)
18:33:28 T:2796544928   DEBUG: Thread JobWorker 2796544928 terminating (autodelete)
18:33:28 T:2947539872   DEBUG: Thread JobWorker 2947539872 terminating (autodelete)
18:33:29 T:3035361280   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/players/VideoPlayer/libdvdnav-arm.so)
18:33:40 T:3035361280   DEBUG: Keyboard: scancode: 0x6c, sym: 0x0112, unicode: 0x0000, modifier: 0x0
18:33:40 T:3035361280   DEBUG: OnKey: down (0xf081) pressed, action is Down
18:33:40 T:3035361280   DEBUG: Keyboard: scancode: 0x6c, sym: 0x0112, unicode: 0x0000, modifier: 0x0
18:33:41 T:3035361280   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
18:33:41 T:3035361280   DEBUG: OnKey: return (0xf00d) pressed, action is Select
18:33:41 T:3035361280   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
18:33:41 T:3035361280   DEBUG: Loading settings for pvr://channels/tv/All channels/pvr.stalker_489858824.pvr
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers(pvr://channels/tv/All channels/pvr.stalker_489858824.pvr)
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
18:33:41 T:3035361280   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
18:33:41 T:3035361280   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
18:33:41 T:3035361280   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData
18:33:41 T:3035361280  NOTICE: VideoPlayer: Opening: pvr://channels/tv/All channels/pvr.stalker_489858824.pvr
18:33:41 T:3035361280 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:33:41 T:3035361280   DEBUG: LinuxRendererGL: Cleaning up GL resources
18:33:41 T:2947539872   DEBUG: Thread VideoPlayer start, auto delete: false
18:33:41 T:2947539872  NOTICE: Creating InputStream
18:33:41 T:2947539872   DEBUG: PVRManager - OpenLiveStream - opening live stream on channel '1+1 international'
18:33:41 T:2947539872   DEBUG: opening live stream on url 'pvr://stream/489858824'
18:33:41 T:2947539872   DEBUG: CDVDInputStreamPVRManager - Open - playback has started on filename pvr://channels/tv/All channels/pvr.stalker_489858824.pvr
18:33:41 T:2947539872   DEBUG: AddOnLog: Stalker Client: GetChannelStreamURL
18:33:41 T:2947539872   DEBUG: AddOnLog: Stalker Client: GetStreamURL
18:33:41 T:2947539872   ERROR: AddOnLog: Stalker Client: GetChannelStreamURL: no stream url found
18:33:41 T:2947539872   DEBUG: CAddonCallbacksAddon - QueueNotification - Stalker Client - Error Message : 'Failed to get stream URL.'
18:33:41 T:2947539872   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/players/VideoPlayer/libdvdnav-arm.so)
18:33:41 T:2947539872   DEBUG: Loading: /usr/lib/kodi/system/players/VideoPlayer/libdvdnav-arm.so
18:33:41 T:2947539872    INFO:   msg: libdvdnav: Using dvdnav version 5.0.4
18:33:41 T:2947539872    INFO:   msg: libdvdread: Can't stat
18:33:41 T:2947539872    INFO:   msg: libdvdread: Could not open
18:33:41 T:2947539872   DEBUG:   msg: libdvdnav: vm: failed to open/read the DVD
18:33:41 T:2947539872   ERROR: Error on dvdnav_open
18:33:41 T:2947539872   ERROR: CDVDInputStreamPVRManager::Open - error opening []
18:33:41 T:2947539872   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.stalker_489858824.pvr]
18:33:41 T:2947539872  NOTICE: CVideoPlayer::OnExit()
18:33:41 T:2947539872   DEBUG: CDVDInputStreamPVRManager::Close - stream closed
18:33:41 T:2796544928   DEBUG: Thread JobWorker start, auto delete: true
18:33:41 T:2947539872   DEBUG: OnPlayBackStopped: play state was 1, starting 1
18:33:41 T:2947539872   DEBUG: Thread VideoPlayer 2947539872 terminating
18:33:41 T:3035361280   DEBUG: OnPlayBackStopped: play state was 3, starting 0
18:33:41 T:3035354016   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
18:33:41 T:3035361280   DEBUG: ------ Window Init (DialogNotification.xml) ------
18:33:41 T:3035354016   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
18:33:41 T:3035361280  NOTICE: CVideoPlayer::CloseFile()
18:33:41 T:3035361280  NOTICE: VideoPlayer: waiting for threads to exit
18:33:41 T:3035361280  NOTICE: VideoPlayer: finished waiting
18:33:41 T:3035361280   DEBUG: DeleteRenderer - deleting renderer
18:33:41 T:3035361280   DEBUG: LinuxRendererGL: Cleaning up GL resources
18:33:41 T:3035361280  NOTICE: CVideoPlayer::CloseFile()
18:33:41 T:3035361280  NOTICE: VideoPlayer: waiting for threads to exit
18:33:41 T:3035361280  NOTICE: VideoPlayer: finished waiting
18:33:41 T:3035361280   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
18:33:44 T:3035361280   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
18:33:47 T:2692740000   DEBUG: AddOnLog: Stalker Client: UnloadEPG

**Comment by kenji123** [comment]
the first bug is fixable

as for the playback, `GetChannelStreamURL: no stream url found`. the addon doesn't print out the command that it's trying to get the url from, so it's tough to know what the problem is there

**Comment by Goga777** [comment]
may be after the fix of the first bug I will return to default option "Provider format" -  {not xmltv only} and  the stream will play. Do you plan to fix the pvr-stalker soon ?

**Comment by kenji123** [comment]
should be fixed in the next or tomorrow's LibreELEC nightly

**Comment by RedManMark86** [comment]
Hi Kenji123, sorry to jump in on this but how do I contact you if I wanted to go about hiring you to do a customised addon that would just be one you currently doing slightly changed?

Thanks,

Mark

**Comment by Goga777** [comment]
have you already updated the stalker in LE repo ?

**Comment by kenji123** [comment]
starting since this build
http://forum.kodi.tv/showthread.php?tid=269815&pid=2418030#pid2418030

**Comment by Goga777** [comment]
I compiled for wetek play according wiki master LE and still see pvr stalker version 2.7.1

**Comment by kenji123** [comment]
Looks like pvr add-ons haven't been updated in master yet.

You can manually bump it by changing the `PKG_VERSION` value to "168e35f" in `packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk`

**Comment by Goga777** [comment]
it was

PKG_NAME="pvr.stalker"
PKG_VERSION="7df63b2"

**Comment by Goga777** [comment]
I have corrected package.mk , re-compiled agai {with cache cleaning before} but after installation on wetek I again see 2.7.1 version in pvr addon list. 

In official LE addon repo I still see 2.7.1 version

**Comment by Goga777** [comment]
I tried to compile pvr addon according your instriction , but after pvr stalker installation I have the error 

ERROR: Unable to load /storage/.kodi/addons/pvr.stalker/pvr.stalker.so.2.8.0, reason: /storage/.kodi/addons/pvr.stalker/pvr.stalker.so.2.8.0: cannot open shared object file: No such file or directory

But pvr.stalker.so.2.8.0 exists in /storage/.kodi/addons/pvr.stalker/. I suspect that for wetek play need some special option/flag for compilation. Which one ? 


LibreELEC:~/.kodi/addons/pvr.stalker # ls -l -L
total 12972
-rw-r--r-- 1 root root 23228 Sep 25 10:33 addon.xml
-rw-r--r-- 1 root root 2984 Sep 25 10:33 changelog.txt
-rw-r--r-- 1 root root 27673 Sep 25 10:33 icon.png
-rw-r--r-- 1 root root 4404368 Sep 25 10:33 pvr.stalker.so
-rw-r--r-- 1 root root 4404368 Sep 25 10:33 pvr.stalker.so.17.0
-rw-r--r-- 1 root root 4404368 Sep 25 10:33 pvr.stalker.so.2.8.0
drwxr-xr-x 3 root root 4096 Sep 25 10:33 resource

**Comment by Goga777** [comment]
thank you for your fix - I don';t  have any crash with 2.8 version
